### ISSUE TITLE
Production not Calling Metamask to Confirm Tx

### ISSUE THREAD

**Issue by lrgeoemtry** [HERCone/herc-igvc-registrar#12]
@kumavis @arachnid
hey, having trouble understanding why this simple ens dapp isn't calling Metamask when loading / when making a new subdomain. 
https://ipfs.infura.io/ipfs/QmQ7X4fE2BkoqMp6faBJQokP9FVE1V4HQ6vpqwxTiJrp2y/

any help helps :) 

also congrats @arachnid on your wedding! 🥇

**Comment by lrgeoemtry** [comment]
@mul1sh maybe you can weigh in here?

**Comment by mul1sh** [comment]
@lrgeoemtry its because the metamask api changed, so this dApp is not detecting metamask at all. But its an easy fix, I can sort it if you want.
